### ISSUE TITLE
Change the background-color of the viewer

### ISSUE THREAD

**Issue by Barrier-Theo** [iberan/pdfjs-flipbook#2]
Hello,

How to change the background-color of the viewer to white ? 

Is is possible to style the css ?

Best regards.

**Comment by iberan** [comment]
In /web/viewer.css #175 change this:

``
body {
  height: 100%;
  background-color: #404040;
  background-image: url(images/texture.png);
}
``

to this:

``
body {
  height: 100%;
  background-color: #fff;
  /*background-image: url(images/texture.png);*/
}
``

Save the file, clear your browser cache and call the viewer again.

**Comment by Barrier-Theo** [comment]
Oh thanks didn't notice there was a body css >_<. 

it works thanks you.
